Repository RevenueCat/docs, pull requests merged in 2025-01, with the labels that each got.

#581 Update API v2 OpenAPI Specifications
  openapi-spec/api-v2-beta.yaml
  openapi-spec/api-v2.yaml
Labels: update, automated-pr

#589 Add Cordova & Capacitor Code Blocks for Redeeming Win-Back Offers on Custom Paywalls
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-capacitor.ts
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-cordova.js
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-capacitor.ts
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-cordova.js
  docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
Labels: documentation

#598 Update .SetObserverMode calls in Unity
  code_blocks/customers/user-ids_16.cs
  code_blocks/migrating-to-revenuecat/observer-mode_6.cs
  docs/migrating-to-revenuecat/sdk-or-not/finishing-transactions.mdx
Labels: documentation

#617 Add info box about version availability
  docs/customers/trusted-entitlements.mdx
Labels: documentation

#622 Specify what id they will get in their webhooks
  docs/customers/user-ids.mdx
Labels: documentation

#627 Add KMP + Unity winback code samples
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-kmp.kt
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-fetch-eligible-winback-offers-unity.cs
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-kmp.kt
  code_blocks/subscription-guidance/subscription-offers/ios-winback-offers-purchase-winback-offer-unity.cs
  docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
Labels: enhancement
