Repository RevenueCat/docs, pull requests merged in 2025-02, with the labels that each got.

#635 Update API v2 OpenAPI Specifications
  openapi-spec/api-v2-beta.yaml
  openapi-spec/api-v2.yaml
Labels: update, automated-pr

#639 Update API v2 OpenAPI Specifications
  openapi-spec/api-v2-beta.yaml
  openapi-spec/api-v2.yaml
Labels: update, automated-pr

#638 Ensures missing SDKs are listed on the 'Troubleshooting SDKs' page.
  docs/test-and-launch/debugging/troubleshooting-the-sdks.mdx
Labels: documentation

#644 Win-Back Doc Tweaks
  docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
  static/images/win-back-offers/win-back-offer-url-app-store-connect.png
Labels: documentation

#646 Remove flaky sandbox win-back message testing warning
  docs/subscription-guidance/subscription-offers/ios-subscription-offers.mdx
Labels: documentation

#651 correctly name objc code block
  docs/getting-started/restoring-purchases.mdx
Labels: bug, documentation
